[package]
name = "cargo-thank-you-stars"
version = "0.1.0"
authors = ["woxtu <woxtup@gmail.com>"]

[dependencies]
error-chain = "0.10.0"
reqwest = "0.7.3"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
toml = "0.4.5"
url = "1.5.1"
